dist: xenial

language: python

python:
  - "3.7"

services:
  - docker

before_install:
  - docker build . -t stock-symbol-service:0.1
  - docker images
  - docker run -d -p 127.0.0.1:8080:5000 stock-symbol-service:0.1

script:
  - bash test.sh

